---
# Install docker-ce
- name: "Add docker-ce apt key"
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    id: "0EBFCD88"
- name: "Add apt repository of docker-ce"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} {{ dokku_docker_ce_channel }}"
- name: "Install docker-ce"
  apt: name=docker-ce
